// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sleego} from '../models';

export function GetConfig():Promise<sleego.FileConfig>;

export function GetRunningProcesses():Promise<Array<sleego.ProcessInfo>>;

export function IsRunning():Promise<boolean>;

export function Run():Promise<void>;

export function SaveConfig(arg1:sleego.FileConfig):Promise<void>;

export function Stop():Promise<void>;
