// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetRunningProcesses() {
  return window['go']['main']['App']['GetRunningProcesses']();
}

export function Hide() {
  return window['go']['main']['App']['Hide']();
}

export function IsRunning() {
  return window['go']['main']['App']['IsRunning']();
}

export function Run() {
  return window['go']['main']['App']['Run']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}
